name: Build and Package (win)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  package:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Dir Listing
        run: |
          tree "C:\Program Files (x86)\Windows Kits\10"

      - name: Package application
        run: |
          python3 test.py
